[package]
name = "barril"
version = "0.1.0"
description = "An async implementation of bitcask"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bytes = "1.6.0"
smol = "2.0.0"
thiserror = "1.0.61"
[lints]
workspace = true
